name: 'BitCraft Game Data'
description: 'Fetches BitCraft game data (desc tables, etc) from STDB and saves JSON to git.'
inputs:
  data-dir:
    required: true
    description: Root directory to put files in
  bitcraft-spacetime-host:
    required: true
    description: Hostname of bitcraft-global module
  stdb-auth:
    required: false
    description: Auth header value, anonymous if not provided
outputs:
  updated_data:
    description: true if something was updated
    value: ${{ steps.game-data.outputs.updated_data }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - run: python -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - run: rm -rf "${{ inputs.data-dir}}"/*
      shell: bash
    - run: python ${{ github.action_path }}/game_data.py
      id: game-data
      shell: bash
      env:
        DATA_DIR: ${{ inputs.data-dir }}
        BITCRAFT_SPACETIME_HOST: ${{ inputs.bitcraft-spacetime-host }}
        BITCRAFT_SPACETIME_AUTH: ${{ inputs.stdb-auth }}

